server:
  port: 8881

spring:
  #  数据库
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  #  消息队列
  activemq:
    broker-url: tcp://192.168.1.172:61616
    user: admin
    password: admin
    in-memory: false
    pool:
      enabled: false
    packages:
      trust-all: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

